using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Prism.Avalonia.Mobile.SourceGen;

/// <summary>
/// Generates compile-time ViewModel type mappings for AOT compatibility.
/// NOTE: Does NOT generate `new ViewModel()` calls for DI-dependent types.
/// ViewModels with constructor dependencies are resolved via DI container.
/// </summary>
[Generator]
public class ViewModelFactoryGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var viewModelClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) =>
                    node is ClassDeclarationSyntax { BaseList: not null },
                transform: static (ctx, _) => GetViewModelInfo(ctx))
            .Where(static info => info is not null);

        context.RegisterSourceOutput(viewModelClasses.Collect(), static (spc, viewModels) =>
        {
            var sb = new System.Text.StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine();
            sb.AppendLine("namespace Prism.Mvvm;");
            sb.AppendLine();
            sb.AppendLine("internal static class ViewModelFactory");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Gets ViewModel type for a view type. Returns null if no mapping exists.");
            sb.AppendLine("    /// Does NOT instantiate — DI constructor resolution is done by the container.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static Type? GetViewModelType(Type viewType) =>");
            sb.AppendLine("        viewType switch");
            sb.AppendLine("        {");

            foreach (var item in viewModels)
            {
                if (item is { } vm && vm.ViewTypeName is not null)
                {
                    sb.AppendLine($"            _ when _ == typeof({vm.ViewTypeName}) => typeof({vm.ViewModelTypeName}),");
                }
            }

            sb.AppendLine("            _ => null");
            sb.AppendLine("        };");
            sb.AppendLine("}");

            spc.AddSource("ViewModelFactory.g.cs",
                SourceText.From(sb.ToString(), System.Text.Encoding.UTF8));
        });
    }

    private static ViewModelInfo? GetViewModelInfo(GeneratorSyntaxContext ctx)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.Node;
        var model = ctx.SemanticModel;
        var symbol = model.GetDeclaredSymbol(classDecl);
        if (symbol is not INamedTypeSymbol namedType) return null;

        // Only match classes with "ViewModel" suffix
        if (!namedType.Name.EndsWith("ViewModel")) return null;

        // Find the corresponding View type (same namespace, replace "ViewModel" with "" for view)
        var baseType = namedType.BaseType;
        var isPrismVM = false;
        while (baseType is not null)
        {
            if (baseType.Name.Contains("BindableBase") ||
                baseType.Name.Contains("ViewModelBase") ||
                baseType.Name.Contains("ObservableObject"))
            {
                isPrismVM = true;
                break;
            }
            baseType = baseType.BaseType;
        }

        if (!isPrismVM) return null;
        if (namedType.IsAbstract || namedType.TypeParameters.Length > 0) return null;

        // Try to find matching View type
        var viewName = namedType.Name.Replace("ViewModel", "");
        var viewNamespace = namedType.ContainingNamespace?.ToDisplayString()
            ?.Replace("ViewModels", "Views");
        var viewTypeName = viewNamespace is not null ? $"{viewNamespace}.{viewName}" : null;

        return new ViewModelInfo(viewTypeName, namedType.ToDisplayString());
    }

    private sealed class ViewModelInfo
    {
        public string? ViewTypeName { get; }
        public string ViewModelTypeName { get; }

        public ViewModelInfo(string? viewTypeName, string viewModelTypeName)
        {
            ViewTypeName = viewTypeName;
            ViewModelTypeName = viewModelTypeName;
        }
    }
}
